### PR TITLE
Added PyCon Canada 2015

### PR DESCRIPTION
**Pull request by dhoffman34**

### CODE REVIEW

**Comment by willkg** [comment]
Thank you for doing this work! 

I have a couple of nits:
1. It looks like the titles have the speaker at the end of them. Can you extract the speaker from the title and put it in the speakers field?
2. The "category" field should have "PyCon CA 2015" for all the videos.

Can you make those changes? After that, I'd be happy to land this.

This is great! Thank you!

**Comment by redapple** [comment]
@dhoffman34 @willkg , PR ready for review: https://github.com/pyconca/pyvideo-data/pull/1

**Comment by dhoffman34** [comment]
@redapple, thanks!

@willkg, looks like this should be ready now.

**Comment by willkg** [comment]
@dhoffman34 @redapple This looks great! Thank you!

**Pull request merged**
