### PR TITLE
Convert markdown to reST

### PR DESCRIPTION
**Pull request by logston**
I used the following script to convert all summary/description data to rst. 

``` python
import lib
import subprocess


def convert_str(string):
    with open('temp', 'w') as fp:
        fp.write(string)

    subprocess.run(['pandoc', 'temp', '-f', 'markdown', '-t', 'rst', '-o', 'out'])

    with open('out') as fp:
        return fp.read()


def main():
    keys = {'summary', 'description'}
    data = lib.load_json_data('.')

    for path, info in data:
        for key in keys:
            string = info.get(key) or ''
            if string.strip():
                new_string = convert_str(string)
                if new_string != string:
                    info[key] = new_string

    lib.save_json_data(data)


main()
```

The imported `lib` is the `lib.py` from clive.

### CODE REVIEW

**Comment by redapple** [comment]
Related to https://github.com/pyvideo/pyvideo-data/issues/27

**Comment by willkg** [comment]
Nice!

How does this handle parsing issues? My concern is that we're stomping on the existing summary/description values and if we hit a parsing error, then we might lose the data.

I think one possibility is that we only do one conference at a time and pour over the changes and undo any changes that involve parsing errors.

Another possibility is the script detects the parsing error. Maybe by opening `out` and then seeing if parsing error strings are in there? Maybe pandoc returns a non-zero status code?

What do you think?

**Comment by redapple** [comment]
@logston , have you tried using `pypandoc` or [`pyandoc`](https://github.com/kennethreitz/pyandoc) instead of a subprocess?

**Comment by logston** [comment]
@willkg Hey! No it does not take parsing into concern but that's a great point and was a concern of mine as well. I think the one conference at a time is a good plan. Maybe we could also build a script to render each rst string and visually check that; I feel that would be the quickest way to manually check the transcription. 

@redapple I haven't tried `pypandoc` but its looks nice. v2 will use that instead.

**Comment by willkg** [comment]
@logston I think rendering and checking a sample is probably fine. This is a one-off script, so it just needs to solve the problem once--it's not something that needs to be engineered for the long term. Let me know if there's anything I can do to help!

**Comment by logston** [comment]
Closing this PR in favor of opening 74 smaller ones

**Pull request closed without merging**
