### PR TITLE
djangocon-2013

### PR DESCRIPTION
**Pull request by logston**

### CODE REVIEW

**Comment by redapple** [comment]
Same comment as for https://github.com/pyvideo/pyvideo-data/pull/31#issuecomment-217870792,
speaker information formatting (2nd line of summary) is lost in the reST conversion
e.g

```
 -  "summary": "Be Agile, Not Vulnerable\nJacob Kaplan-Moss\n\nAudience level: Novice\n\nDescription\n\nSecurity has to be everyone's responsibility, and cannot be managed as a feature.\n\nAbstract\n\nStartups like to \"move fast and break things\"... but how do you ensure that what breaks isn't security? How do you strike a balance and make sure you're able to ship quickly while still ensuring that what goes out the door doesn't have vulnerabilities? The answer begins by recognizing that security is a process, not a feature, and this has ramifications throughout the organization. It means that security engineering needs to be everyone's responsibility (instead of a select few), and it means that when security vulnerabilities crop up \u2014 and they will \u2014 the organization needs to be prepared and aligned to act quickly.",
 +  "summary": "Be Agile, Not Vulnerable Jacob Kaplan-Moss\n\nAudience level: Novice\n\nDescription\n\nSecurity has to be everyone's responsibility, and cannot be managed as a\nfeature.\n\nAbstract\n\nStartups like to \"move fast and break things\"... but how do you ensure\nthat what breaks isn't security? How do you strike a balance and make\nsure you're able to ship quickly while still ensuring that what goes out\nthe door doesn't have vulnerabilities? The answer begins by recognizing\nthat security is a process, not a feature, and this has ramifications\nthroughout the organization. It means that security engineering needs to\nbe everyone's responsibility (instead of a select few), and it means\nthat when security vulnerabilities crop up \u2014 and they will \u2014 the\norganization needs to be prepared and aligned to act quickly.\n",
```

if we could fix the markdowned data to extract speakers first, it would be best.

**Comment by logston** [comment]
Ouch, good catch. Since its kind of a hard thing to search for programmatically, I think the quickest route would be to hand update these changes. I might be able to get to this this weekend.

**Comment by redapple** [comment]
#118 ready for review

**Comment by willkg** [comment]
Nixing this in favor of #118.

Thank you!

**Pull request closed without merging**
