### PR TITLE
Fixed my name

### PR DESCRIPTION
**Pull request by MarkusH**

### CODE REVIEW

**Comment by willkg** [comment]
A couple of things happened over the last 24 hours or so that I think suggest that we're going to EOL this repository in favor of the pytube fork at https://github.com/pytube/pyvideo-data .

Can you submit this PR and future PRs there?

**Comment by willkg** [comment]
Also, I really apologize for getting your name wrong. Sorry about that.

**Comment by willkg** [comment]
Merging this. Thank you!

**Comment by MarkusH** [comment]
> Also, I really apologize for getting your name wrong. Sorry about that.

Not a problem, that's wrong on the source.

**Pull request merged**
