### PR TITLE
djangocon-2014

### PR DESCRIPTION
**Pull request by logston**

### CODE REVIEW

**Comment by redapple** [comment]
I believe speaker(s) information could be parsed before converting to .rst.

In this PR, speaker information gets merged into the first line, making it more difficult to work on speakers later, while in the original markdown format, it's on its own line (although without any "speakers" data).

[for example](https://github.com/pyvideo/pyvideo-data/pull/31/files#diff-faf8ed154cb275941aaf7ea1dcca97baL5):

```
-  "summary": "By, Joshua \"jag\" Ginsberg\n\"Don't prematurely optimize. Get your project to v1.0.\" This is a mantra often repeated in the Djangoverse. But what happens after v1.0 launch when your awesome site is being crushed by traffic? Scaling Django under load means finding bottlenecks, leveraging new tools, and customizing code. This talk will show you how it's done.\n\nHelp us caption & translate this video!\n\nhttp://amara.org/v/FOPX/",
+  "summary": "By, Joshua \"jag\" Ginsberg \"Don't prematurely optimize. Get your project\nto v1.0.\" This is a mantra often repeated in the Djangoverse. But what\nhappens after v1.0 launch when your awesome site is being crushed by\ntraffic? Scaling Django under load means finding bottlenecks, leveraging\nnew tools, and customizing code. This talk will show you how it's done.\n\nHelp us caption & translate this video!\n\nhttp://amara.org/v/FOPX/\n",
```

**Comment by willkg** [comment]
@redapple I think that makes sense. Maybe we should do a new PR based on the master branch to fix the speaker information. Then we can re-run the format translation script and create a new MD -> reST PR.

Can you do that work?

If not, then I think I'd rather just land this PR as is and open up a new issue for fixing the speaker information for djangocon 2014 later.

**Comment by codersquid** [comment]
I'll review this later today for any data loss.

@redapple I think cleaning up content is an okay goal, but I'd rather have it as a separate request after we get all of these outstanding requests handled. People can make PRs to tidy data, or open issues if they don't have to time at the moment.

**Comment by redapple** [comment]
@willkg , done in https://github.com/pyvideo/pyvideo-data/issues/107

@codersquid , I understand. I just spotted this while starting reviewing @logston 's PRs and wanted to prevent speaker data "loss" (of course, it's recoverable as it is)

**Comment by codersquid** [comment]
Thanks @redapple!

(minor logistical thing. I will unassign myself from reviewing this PR since you are on it. If you've been working on others, leave a comment so I don't pick them up.)

**Comment by redapple** [comment]
I believe this one can now be closed (#116 being merged)

**Comment by willkg** [comment]
Yup! Thank you!

**Pull request closed without merging**
